### ISSUE TITLE
Should this be on pressed or the app loads straight into then menu?

### ISSUE THREAD

**Issue by ted-marozzi** [ted-marozzi/alg-io#4]
https://github.com/ted-marozzi/alg-io/blob/52b73ac2830ac4b28e827cb1b34f0690a3ce56ae/lib/main.dart#L57

Is the intended behaviour to make the user press to continue or should it just flash the logo and continue onto the menu?

**Comment by callumj2** [comment]
I like the idea of pressing to enter but either works fine 👍

**Comment by ted-marozzi** [comment]
Okay **cool**.
